---
- hosts: localhost
  tasks:
    - name: create key pair using key_material obtained using 'file' lookup plugin
      amazon.aws.ec2_key:
        name: saitama
        key_material: "{{ lookup('file', '~/Desktop/infra2/clase5/ansible/saitama.pub') }}"