---
- hosts: localhost
  tasks:
    - name: Creamos nuestro servidor
      ec2:
        region: us-east-1
        instance_type: t2.micro
        image: ami-053b0d53c279acc90
        keypair: pochita
        wait: yes
        wait_timeout: 500
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 8
        vpc_subnet_id: subnet-046fa660fb8892f9c
        assign_public_ip: yes