---
- hosts: localhost
  tasks:
    - name: Crear una instancia EC2 con ip publica
      amazon.aws.ec2_instance:
        name: instanciaEC2
        key_name: pochita
        instance_type: t2.micro
        count: 3
        network:
          assign_public_ip: true
        image_id: ami-09cd747c78a9add63
