# una referencia a la versión del template de los
# módulos que vamos a utilizar. La versión “2010-09-09”
# es la vigente en 2021.
AWSTemplateFormatVersion: 2010-09-09

# una pequeña descripción de qué vamos a hacer.
Description: Automatizamos Bucket S3 

# Vamos a ingresar el nombre del bucket por parámetro, es decir, 
# por fuera del template al momento que lo ejecutamos.
Parameters:
  BucketName:
    Type: String
    Description: El nombre de mi Bucket S3

# En el espacio de Metadata se define la información que mostramos en la 
# interfaz gráfica
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Bucket S3
        Parameters:
          - BucketName
    ParameterLabels:
      BucketName:
        default: 'Nombre de mi Bucket:'

# El recurso a crear. El código escrito anteriormente es para darle un 
# contexto al recurso que necesitamos, nuestro bucket S3. 
# En este espacio definimos que queremos crear el bucket y dentro de sus 
# propiedades:
#     ● El nombre se recibe por parámetro (!REF + nombre de variable, definida 
#       arriba).
#     ● Deshabilitar la visibilidad pública para que nuestro bucket sea privado.
#     ● Habilitamos el versionado de los archivos que vamos a almacenar.

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:

      # Tiene que recibir el nombre del bucket por parámetro.
      BucketName: !Ref BucketName 

      # El bucket debe ser privado.
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      # Tenemos que activar el versionado del bucket.
      VersioningConfiguration: 
        Status: Enabled

